In [1]:
from Dataset import MatrixGenerator

In [2]:
import json
params_str = json.dumps({
    "m": 50,                 # Number of rows
    "n": 50,                 # Number of columns
    "rank": 10,              # Rank of the original matrix
    "missing_fraction": 0.5, # 50% of the entries will be missing
    "noise_level": 0,        # Standard deviation of Gaussian noise
    "num_iters": 5000,        # Maximum number of iterations for completion
    "tol": 1e-9,             # Convergence tolerance, np.inf if it not need

    "alpha": 0.33           # Another custom parametrs
})

In [3]:
MG = MatrixGenerator()
random_matrix, missing_mask = MG.get_matrix(m=50, n=50, k=10, random_state=42, missing_fraction=0.2, noise_level=0)
random_matrix, missing_mask

(array([[-1.65816428, -1.03565299, -3.00908319, ..., -1.16309223,
          3.07041517,  3.39692719],
        [ 0.12019511,  0.18088462,  4.30482148, ...,  3.60266947,
         -1.13175039,  2.07573298],
        [ 0.90046414,  0.85976975, -1.21270152, ...,  1.70091531,
         -0.34410166,  0.58313111],
        ...,
        [-4.10182697, -0.8424992 , -0.94991737, ..., -5.93721224,
          0.97663351,  2.62569084],
        [ 2.2699357 ,  1.1379267 ,  4.66042693, ...,  3.08816334,
          0.41678119,  1.0257088 ],
        [ 2.8572988 , -1.24423194,  0.84161185, ..., -0.81378704,
         -1.61016078, -6.41038886]], shape=(50, 50)),
 array([[ True,  True,  True, ...,  True,  True,  True],
        [ True, False,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True, False],
        ...,
        [ True,  True,  True, ..., False,  True,  True],
        [ True,  True,  True, ...,  True,  True, False],
        [ True,  True, False, ...,  True,  True, False]], s

In [4]:
import numpy as np
from algorithms.RCGMatrixCompletion import RCGMatrixCompletion

MC = RCGMatrixCompletion(params_str=params_str)
factorization = MC.complete_matrix(random_matrix, missing_mask, "rdg", "QPRECON")

Iter 0: Cost=646.619653, GradNorm=3.757551e+00
Iter 10: Cost=395.356933, GradNorm=2.419578e+00
Iter 20: Cost=283.026042, GradNorm=1.725428e+00
Iter 30: Cost=230.521821, GradNorm=1.307615e+00
Iter 40: Cost=204.018315, GradNorm=1.045432e+00
Iter 50: Cost=189.160715, GradNorm=8.717714e-01
Iter 60: Cost=180.033495, GradNorm=7.502709e-01
Iter 70: Cost=174.006982, GradNorm=6.611707e-01
Iter 80: Cost=169.798029, GradNorm=5.932672e-01
Iter 90: Cost=166.725830, GradNorm=5.398747e-01
Iter 100: Cost=164.402868, GradNorm=4.968062e-01
Iter 110: Cost=162.595343, GradNorm=4.613249e-01
Iter 120: Cost=161.155200, GradNorm=4.315745e-01
Iter 130: Cost=159.984804, GradNorm=4.062552e-01
Iter 140: Cost=159.017511, GradNorm=3.844314e-01
Iter 150: Cost=158.206477, GradNorm=3.654133e-01
Iter 160: Cost=157.517925, GradNorm=3.486814e-01
Iter 170: Cost=156.926955, GradNorm=3.338375e-01
Iter 180: Cost=156.414853, GradNorm=3.205711e-01
Iter 190: Cost=155.967305, GradNorm=3.086367e-01
Iter 200: Cost=155.573199, Grad

In [5]:
factorization = MC.complete_matrix(random_matrix, missing_mask, "rcg", "QPRECON")

Iter 0: Cost=646.619653, GradNorm=3.757551e+00
Iter 10: Cost=235.916520, GradNorm=1.411202e+00
Iter 20: Cost=170.865070, GradNorm=6.038141e-01
Iter 30: Cost=159.238507, GradNorm=3.902267e-01
Iter 40: Cost=155.165585, GradNorm=2.848225e-01
Iter 50: Cost=153.373419, GradNorm=2.262468e-01


Iter 60: Cost=152.423362, GradNorm=1.921021e-01
Iter 70: Cost=151.878343, GradNorm=1.712364e-01
Iter 80: Cost=151.564490, GradNorm=1.583897e-01
Iter 90: Cost=151.395692, GradNorm=1.510513e-01
Iter 100: Cost=151.323521, GradNorm=1.477803e-01
Iter 110: Cost=151.271671, GradNorm=1.453633e-01
Iter 120: Cost=151.214396, GradNorm=1.426334e-01
Iter 130: Cost=151.152695, GradNorm=1.396285e-01
Iter 140: Cost=151.087572, GradNorm=1.363889e-01
Iter 150: Cost=151.020002, GradNorm=1.329560e-01
Iter 160: Cost=150.950902, GradNorm=1.293703e-01
Iter 170: Cost=150.881113, GradNorm=1.256709e-01
Iter 180: Cost=150.811384, GradNorm=1.218944e-01
Iter 190: Cost=150.742365, GradNorm=1.180739e-01
Iter 200: Cost=150.674602, GradNorm=1.142386e-01
Iter 210: Cost=150.608548, GradNorm=1.104140e-01
Iter 220: Cost=150.544561, GradNorm=1.066213e-01
Iter 230: Cost=150.482914, GradNorm=1.028779e-01
Iter 240: Cost=150.423809, GradNorm=9.919754e-02
Iter 250: Cost=150.367383, GradNorm=9.559080e-02
Iter 260: Cost=150.31371

In [6]:
params_str = json.dumps({
    "m": 50,                 # Number of rows
    "n": 50,                 # Number of columns
    "rank": 10,              # Rank of the original matrix
    "missing_fraction": 0.5, # 50% of the entries will be missing
    "noise_level": 0,        # Standard deviation of Gaussian noise
    "num_iters": 700,        # Maximum number of iterations for completion
    "tol": 1e-9,             # Convergence tolerance, np.inf if it not need

    "alpha": 0.33           # Another custom parametrs
})

In [7]:
MC_3 = RCGMatrixCompletion(params_str=params_str)
factorization = MC_3.complete_matrix(random_matrix, missing_mask, "rdg", "QRIGHT-INV")

Iter 0: Cost=646.619653, GradNorm=7.530651e+03
Iter 10: Cost=278.058087, GradNorm=2.117118e+03
Iter 20: Cost=208.808415, GradNorm=1.087602e+03
Iter 30: Cost=183.626023, GradNorm=6.722611e+02
Iter 40: Cost=171.174387, GradNorm=4.718679e+02
Iter 50: Cost=163.835265, GradNorm=3.590530e+02
Iter 60: Cost=159.117401, GradNorm=2.856519e+02
Iter 70: Cost=155.970690, GradNorm=2.317942e+02
Iter 80: Cost=153.658329, GradNorm=1.849726e+02
Iter 90: Cost=151.941360, GradNorm=1.409154e+02


Iter 100: Cost=150.752602, GradNorm=9.926599e+01
Iter 110: Cost=150.019967, GradNorm=6.057628e+01
Iter 120: Cost=149.666026, GradNorm=2.712824e+01
Iter 130: Cost=149.586502, GradNorm=1.082332e+01
Iter 140: Cost=149.581880, GradNorm=9.172284e+00
Iter 150: Cost=149.578722, GradNorm=7.886755e+00
Iter 160: Cost=149.576406, GradNorm=6.825315e+00
Iter 170: Cost=149.574688, GradNorm=5.948353e+00
Iter 180: Cost=149.573399, GradNorm=5.223429e+00
Iter 190: Cost=149.572419, GradNorm=4.623873e+00
Iter 200: Cost=149.571664, GradNorm=4.127664e+00
Iter 210: Cost=149.571073, GradNorm=3.716558e+00
Iter 220: Cost=149.570603, GradNorm=3.375393e+00
Iter 230: Cost=149.570223, GradNorm=3.091557e+00
Iter 240: Cost=149.569911, GradNorm=2.854565e+00
Iter 250: Cost=149.569650, GradNorm=2.655723e+00
Iter 260: Cost=149.569429, GradNorm=2.487856e+00
Iter 270: Cost=149.569238, GradNorm=2.345073e+00
Iter 280: Cost=149.569071, GradNorm=2.222570e+00
Iter 290: Cost=149.568923, GradNorm=2.116452e+00
Iter 300: Cost=149.5

In [8]:
factorization = MC_3.complete_matrix(random_matrix, missing_mask, "rcg", "QRIGHT-INV")

Iter 0: Cost=646.619653, GradNorm=7.530651e+03
Iter 10: Cost=189.195280, GradNorm=1.306016e+03
Iter 20: Cost=154.691633, GradNorm=5.733058e+02
Iter 30: Cost=151.138242, GradNorm=3.277672e+02
Iter 40: Cost=150.631262, GradNorm=2.608918e+02
Iter 50: Cost=149.981566, GradNorm=1.597426e+02
Iter 60: Cost=149.694534, GradNorm=8.451646e+01
Iter 70: Cost=149.599533, GradNorm=4.512660e+01
Iter 80: Cost=149.576448, GradNorm=2.002063e+01
Iter 90: Cost=149.570071, GradNorm=9.446836e+00
Iter 100: Cost=149.568573, GradNorm=4.634621e+00
Iter 110: Cost=149.567883, GradNorm=3.622990e+00
Iter 120: Cost=149.567331, GradNorm=2.841322e+00
Iter 130: Cost=149.566828, GradNorm=2.137627e+00
Iter 140: Cost=149.566571, GradNorm=1.403261e+00
Iter 150: Cost=149.566471, GradNorm=8.938133e-01
Iter 160: Cost=149.566414, GradNorm=6.778628e-01
Iter 170: Cost=149.566383, GradNorm=4.963226e-01
Iter 180: Cost=149.566365, GradNorm=3.475132e-01
Iter 190: Cost=149.566356, GradNorm=2.380728e-01
Iter 200: Cost=149.566352, Grad

In [9]:
MG = MatrixGenerator()
random_matrix, missing_mask = MG.get_matrix(m=50, n=50, k=10, random_state=42, missing_fraction=0.2, noise_level=0)
random_matrix, missing_mask

(array([[-1.65816428, -1.03565299, -3.00908319, ..., -1.16309223,
          3.07041517,  3.39692719],
        [ 0.12019511,  0.18088462,  4.30482148, ...,  3.60266947,
         -1.13175039,  2.07573298],
        [ 0.90046414,  0.85976975, -1.21270152, ...,  1.70091531,
         -0.34410166,  0.58313111],
        ...,
        [-4.10182697, -0.8424992 , -0.94991737, ..., -5.93721224,
          0.97663351,  2.62569084],
        [ 2.2699357 ,  1.1379267 ,  4.66042693, ...,  3.08816334,
          0.41678119,  1.0257088 ],
        [ 2.8572988 , -1.24423194,  0.84161185, ..., -0.81378704,
         -1.61016078, -6.41038886]], shape=(50, 50)),
 array([[ True,  True,  True, ...,  True,  True,  True],
        [ True, False,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True, False],
        ...,
        [ True,  True,  True, ..., False,  True,  True],
        [ True,  True,  True, ...,  True,  True, False],
        [ True,  True, False, ...,  True,  True, False]], s

In [10]:
params_str = json.dumps({
    "m": 100,
    "n": 100,
    "rank": 10,
    "missing_fraction": 0.5,
    "noise_level": 0.1,
    "num_iters": 100,
    "tol": 1e-4,
    "random_state": 42,
})

In [11]:
import numpy as np
from algorithms.LRGeomCGMatrixCompletion import LRGeomCG

MC_5 = LRGeomCG(params_str=params_str)

In [12]:
factorization = MC_5.complete_matrix(
    M=missing_mask * random_matrix,
    Omega=missing_mask,
    k=10,
    M_true=random_matrix
)

  0%|          | 0/100 [00:00<?, ?it/s]/home/a-ploskin/repos/MatrixCompletionAlgorithmsOverview/algorithms/LRGeomCGMatrixCompletion.py:180: RuntimeWarning: divide by zero encountered in scalar divide
  beta = max(0, delta.scalar_product(grad) / grad_prev.norm**2)
/home/a-ploskin/repos/MatrixCompletionAlgorithmsOverview/algorithms/LRGeomCGMatrixCompletion.py:30: RuntimeWarning: invalid value encountered in multiply
  M=self.M * scalar,
/home/a-ploskin/repos/MatrixCompletionAlgorithmsOverview/algorithms/LRGeomCGMatrixCompletion.py:31: RuntimeWarning: invalid value encountered in multiply
  Up=self.Up * scalar,
/home/a-ploskin/repos/MatrixCompletionAlgorithmsOverview/algorithms/LRGeomCGMatrixCompletion.py:32: RuntimeWarning: invalid value encountered in multiply
  Vp=self.Vp * scalar,
/home/a-ploskin/repos/MatrixCompletionAlgorithmsOverview/algorithms/LRGeomCGMatrixCompletion.py:33: RuntimeWarning: invalid value encountered in multiply
  nu=self.nu * scalar
  0%|          | 0/100 [00:00<?

AssertionError: 